### ISSUE TITLE
perf:objects won't boot

### ISSUE THREAD

**Issue by 9mm** [zombocom/derailed_benchmarks#213]
I get this error when running `PATH_TO_HIT=/api/webhooks RAILS_ENV=development bundle exec derailed exec perf:objects`

```
undefined method `migrate' for ActiveRecord::Migrator:Class (NoMethodError)
ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths, nil)
                              ^^^^^^^^
```

Without adding `RAILS_ENV` i also get a huge amount of errors related to all different gems Im not even including in application.rb, like complaining about storage.yml etc. `RAILS_ENV=production rails s` works fine, so I'm not sure what its doing when booting

**Comment by schneems** [comment]
If this is a bug with derailed I need a https://codetriage.com/example_app

**Comment by leoplct** [comment]
I got the same error. It looks `ActiveRecord::Migrator.migrate `is deprecated.

**Comment by pcai** [comment]
Hey @9mm and @leoplct this was *probably* fixed today here: https://github.com/zombocom/derailed_benchmarks/commit/ed7aca1d9b0cd21895941a0ad6942655c5a6d5e7#diff-f664940efc086db824343731b3153f1a5037529d3fd554249805221eb1d98508R44 although i cant be sure since you didnt share the rails version youre using

give the main branch a try and see if it resolves your error. Otherwise, please reopen with an https://codetriage.com/example_app repro
